[project]
title      = "QuakeWatch"
version    = "0.1.0"
port       = 8501
slug       = "quakewatch"
entrypoint = "hello.py"

[branding]
name         = "QuakeWatch"
logo         = "images/logo.png"
favicon      = "images/favicon.ico"
primaryColor = "#1E88E5"
secondaryColor = "#FFB300"

[data.all_month]
type = "csv"
path = "data/all_month.csv"

[logging]
level  = "INFO"
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
